import assert from 'node:assert/strict';
import {archiveSnapshot,partitionHistory,dayKey,groupDays,validArchive} from '../dashboard-history.js';
const at=s=>Date.parse(s),cut=at('2026-10-09T12:00:00Z');
const session={id:'s1',uid:'leo',startedAt:cut-60000,lastSeenAt:cut-1000,activeSeconds:60};
const old={id:'a1',uid:'leo',createdAt:cut-1},same={id:'a2',uid:'leo',createdAt:cut},fresh={id:'a3',uid:'leo',createdAt:cut+1};
const archive=archiveSnapshot([session],cut);
let result=partitionHistory([session],[old,same,fresh],{leo:archive});
assert.deepEqual(result.current.attempts.map(a=>a.id),['a3']);assert.equal(result.archived.attempts.length,2);assert.equal(result.current.sessions.length,0);assert.equal(result.archived.sessions[0].activeSeconds,60);
const continued={...session,lastSeenAt:cut+1000,activeSeconds:75};
result=partitionHistory([continued],[fresh],{leo:archive});assert.equal(result.current.sessions[0].activeSeconds,15);assert.equal(result.archived.sessions[0].activeSeconds,60);assert.equal(result.current.sessions[0].continued,true);
const second=archiveSnapshot([continued],cut+2000);result=partitionHistory([continued],[fresh],{leo:second});assert.equal(result.current.sessions.length,0);assert.equal(result.archived.sessions[0].activeSeconds,75);
result=partitionHistory([{...continued,activeSeconds:80,lastSeenAt:cut+3000}],[],{leo:second});assert.equal(result.current.sessions[0].activeSeconds,5);
result=partitionHistory([session],[old],{});assert.equal(result.current.sessions.length,1);assert.equal(result.current.attempts.length,1);
result=partitionHistory([{...session,uid:'other'}],[{...old,uid:'other'}],{leo:archive});assert.equal(result.current.sessions.length,1);
result=partitionHistory([{...session,id:'late'}],[old],{leo:archive});assert.equal(result.archived.sessions.length,1);
result=partitionHistory([{...session,id:'late-running',lastSeenAt:cut+1}],[],{leo:archive});assert.equal(result.current.sessions.length,1);
assert.equal(dayKey(at('2026-10-09T22:30:00Z')),'2026-10-10');assert.equal(dayKey(at('2026-12-09T23:30:00Z')),'2026-12-10');assert.equal(dayKey(null),'unknown');
assert.deepEqual(groupDays([{displayAt:cut},{displayAt:cut+86400000},{displayAt:0}]).map(x=>x.key),['2026-10-10','2026-10-09','unknown']);
assert.equal(validArchive({version:1,cutoffMs:'bad',baselines:{}}),false);
assert.deepEqual(JSON.parse(JSON.stringify(archive)),archive);assert.equal(session.activeSeconds,60);
console.log('PASS: archive boundaries, same-day scores, ongoing sessions, repeated archives, reset, separate profiles, late arrivals, Paris dates, invalid storage, original data intact.');
